### PR TITLE
Remove obscured password overlay

### LINKED ISSUE #170: Dark theme: Improve readability of obscured password overlay.
Either simply remove the text, or make it stand out better in dark theme. obviously make sure it also looks good in light theme as well ;-)

### PR DESCRIPTION
**Pull request by Trekky12**
Improves readability of protected fields and fixes #170

### CODE REVIEW

**Comment by hpoul** [comment]
I think i would prefer if there is some way to make it work on dark theme without completely removing it 😅️ - have you tried using different colors or something before removing it?
or maybe remove the text but leave the blurring effect.. I kind of liked the look in the light theme.. It would be nice to have some visual effect there i think..

**Comment by Trekky12** [comment]
Oh sorry I didn't recognize the blur effect, but I like it 👍 
I tried some experiments.
How do you like the following colors?

grafik
grafik

**Comment by hpoul** [comment]
👍️ yep thanks, i think this looks better.. have you tried using "normal" foreground color, like the normal text color used by the other fields 🤔️ looks almost white

Screen Shot 2020-10-06 at 19 54 33

**Comment by Trekky12** [comment]
I think the gray comes from the shadow but I could check this tomorrow.

**Comment by Trekky12** [comment]
@hpoul how do you like the white font color?
grafik

**Comment by hpoul** [comment]
👍️ i think it looks good.. ;-) btw. where did the eye icon go? 🤔️
could you rebase or merge from the master?

**Comment by Trekky12** [comment]
@hpoul I merged with the master branch.
Actually I don't know where the eye icon was gone missing but now it is here:
grafik

**Comment by hpoul** [comment]
Looks good to me 🥳 thanks! 👍️

**Pull request merged**
