### PR TITLE
Allowed three column layout with Pin/Unpin option for large tablets

### PR DESCRIPTION
**Pull request by Satendra124**
Fiix #267 
In the  `_buildDefaultAppBar()` at `password_list.dart` added an action for pin/unpin for large tablets
Added drawer to the side of PasswordList when the device width is large enough(1120)

For some reason `androidOverscrollIndicator` was giving me error at `theme.dart` so i commented it out.

### CODE REVIEW

**Comment by Satendra124** [comment]
Attaching some screenshots
unattached
unpinned_view_attached
pin_view attached

**Comment by Satendra124** [comment]
@hpoul hey, if there are changes let me know 😄

**Comment by hpoul** [comment]
sorry for the delayed response..
thanks for your work 👍 works good..

But I think it would be better to put the drawer into the same "level" as the password list, ie. in the `_MainAppTabletScaffoldState` this way there wouldn't be an app bar inside an app bar.. but "panels" next to each other..
So we can add a Pin/Unpin icon directly to the app bar of the group filter. (just like right now the password list is on the same "level" as the entry details.. with app bars next to each other, instead of inside each other).

The main problem is, that currently the whole group filter state and everything is handled directly inside the password list. I think we would have to extract this into it's own view model and manage the state outside the widget tree.
ie. encapsulating `_groupFilterNotifier` and `_groupFilter` from `_PasswordListContentState` into it's own view model or bloc or something. maybe a class like `CurrentGroupFilter` and either just use `Provider` to inject it globally into the app, or create it in the `MainAppScaffold`.

Does this make sense? what do you think?

**Comment by Satendra124** [comment]
Ok, so currently what happens is in the `_PasswordListContentState` holds `GroupFilter` and hence in the drawer `PasswordListDrawer` the arguments `initialSelection` and `selectionChanged` are passed which sets the initial selection and registers some kind of callback to `_PasswordListContentState` to update its state. 
So what you mean is to extract the "group filter" classes by using some global provider and set notifiers to `_PasswordListContentState` instead of the reverse which is happening currently?
image
This is the `_MainAppTabletScaffoldState` Row , just adding the drawer here when the tablet size is large enough should do?
also when the device is not large enough the drawer should work as it is working currently i.e. inside the  `_PasswordListContentState`? 
Also since there is no appbar in `PasswordListDrawer` , we should remove the Heading and add appbar there?

**Comment by Satendra124** [comment]
Hey, can you please suggest if the above is a good approch .. so I would complete and make a new PR?

**Comment by hpoul** [comment]
sorry for the late reply.. a bit busy lately..

> So what you mean is to extract the "group filter" classes by using some global provider and set notifiers to `_PasswordListContentState` instead of the reverse which is happening currently?

good question... I think I would keep the API of the `GroupFilterFlatList` which gets passed an `initialSelection` and a `selectionChanged`.. but I guess we could make a global provider for the `ValueNotifier<GroupFilter> _groupFilterNotifier` which is currently inside `_PasswordListContentState` .. and this will be read/updated by the `PasswordListDrawer` and read by the `_PasswordListContentState` which currently is the owner of that object.. so this is kind of reversed I guess.


> just adding the drawer here when the tablet size is large enough should do?

yes

> when the device is not large enough the drawer should work as it is working currently

like it was before, yes. just passing it as the `drawer` to the `Scaffold`.

> since there is no appbar in PasswordListDrawer , we should remove the Heading and add appbar there

well, it looks like an app bar.. so I wouldn't change anything there.. maybe once we need some actions.. (like back or menus).. but for now I don't think this is necessary..

thanks

**Comment by hpoul** [comment]
I accidentially merged this prematurely. If you are still interested please open a new PR against the latest `main` branch.

**Pull request merged**
