### PR TITLE
copy TOTP and MacOS global hotkey support

### PR DESCRIPTION
**Pull request by rburgst**
this PR adds 2 features to AuthPass: 
- Keyboard Shortcuts for TOTP
- Global Hotkey support for Mac OSX: use `CMD ^ n`  to bring AuthPass to front and invoke the search function

### CODE REVIEW

**Comment by rburgst** [comment]
tried https://pub.dev/packages/hotkey_manager but something completely hosed my project, now i can no longer build (getting weird signing errors). So it might take a while to materialize.

**Comment by rburgst** [comment]
I think the problem is related to https://github.com/leanflutter/hotkey_manager/issues/1

**Comment by rburgst** [comment]
hotkey_manager: 0.0.4 did the trick, @hpoul here is now the multiplatform version

**Comment by rburgst** [comment]
@hpoul I am a bit new to flutter, so I cant figure out why the integration test is failing. I added a catch to the registration of the hotkey but somehow this does not seem to work or the int test. I tested the actual build on the ios simulator and there it looked like the exception was properly caught. 
Not sure what I am doing wrong here.

**Comment by hpoul** [comment]
@rburgst no worries, i think the exception is not catched, because you don't `await` the future. and the exception is actually thrown in asynchronous code and not synchronously. So it ends up in flutters catchall which is probably ignored when running the app, but it produces the integration test to fail..

So you could probably "fix" this by adding an `await` but I think it would be nicer if instead of catching the error you only register on supported platforms.. ie. `if (AuthPassPlatform.isMacOS || AuthPassPlatform.isWindows) { await HotKeyManager.instance.unregister(_hotKey); }` so no try/catch, just an if..

(btw. any idea if the plugin is supported on linux? it seems there is linux code which does *something* but the `README.md` for the plugin states clearly that it lacks linux support 🤔️)

**Comment by lijy91** [comment]
I am the author of hotkey_manager, it will support linux platform soon.

**Comment by rburgst** [comment]
> @rburgst no worries, i think the exception is not catched, because you don't `await` the future.

Ah, that makes sense, the problem is that `KeyboardHandler.initState` is not async and therefore, I cannot `await` the promise (I think)

**Comment by rburgst** [comment]
> So you could probably "fix" this by adding an `await` but I think it would be nicer if instead of catching the error you only register on supported platforms.. ie. `if (AuthPassPlatform.isMacOS || AuthPassPlatform.isWindows) { await HotKeyManager.instance.unregister(_hotKey); }` so no try/catch, just an if..

I am not sure I want to always keep track of which platforms `HotKeyManager` supports. 
I currently worked around the problem via `HotKeyManager.instance.register.catchError`

**Comment by hpoul** [comment]
> always keep track of which platforms `HotKeyManager` supports

It's not like this will change on a weekly basis 😂 
The problem with catching and ignoring is that when a supported platform fails to register, for whatever reason, we would never know and it would be a pain to debug it.. it would be invisible in user logs..

**Comment by hpoul** [comment]
@rburgst thanks, looks good 👍
I've made two changes, maybe you can take a look and see if everything still works for you:

1. require users to enable system wide shortcuts in the preferences https://github.com/authpass/authpass/pull/262/commits/3b8bf28f2579d26c5aeec4ef4ed15554a8470c4c (I don't want to mess with system wide shortcuts without asking)
2. added a fallback to the totp copy https://github.com/authpass/authpass/pull/262/commits/856d3fc011cea2f079e7640c89608255c04ce66a - it now copies either the `otpauth` or `otp` or `totp seed` fields.

Also - what was the thought behind using <kbd>ctrl+alt+n</kbd> as shortcut for search? since the app internal shortcut is <kbd>ctrl+f</kbd> wouldnt it make more sense to use <kbd>ctrl+alt+f</kbd>? 🤔️


(btw. in the future it would be easier if you could create separate PRs for each feature, it would make discussions a bit easier 😅️)

**Comment by rburgst** [comment]
> Also - what was the thought behind using ctrl+alt+n as shortcut for search? since the app internal shortcut is ctrl+f wouldnt it make more sense to use ctrl+alt+f? 🤔️

Actually the keyboard shortcut should be configurable, but I dont have enough knowledge and practice with Flutter to efficiently do this.
I am using IntelliJ/Android Studio on a regular basis and therefore, the list of available shortcut keys is quite short.

**Comment by lijy91** [comment]
@rburgst Please upgrade `hotkey_manager` to `0.0.5`, This version is supported linux platform.

**Comment by rburgst** [comment]
> @rburgst Please upgrade `hotkey_manager` to `0.0.5`, This version is supported linux platform.

done

**Comment by rburgst** [comment]
> (btw. in the future it would be easier if you could create separate PRs for each feature, it would make discussions a bit easier 😅️)

Sorry about that, I was on a roll. Will do that next time.
Anyway, thanks for improving the PR significantly. Can we merge this now?

**Comment by hpoul** [comment]
@rburgst my only concern is the keyboard shortcut <kbd>ctrl+alt+n</kbd> - for me this would make more sense for creating a new password entry :-) i think i'll change it to <kbd>ctrl+alt+f</kbd>, if you don't have a better idea? 🤔️

yes, earlier or later this should be configurable.. but until then it should be a sensible default.. the whole keyboard shortcut implementation is just a workaround right now, honestly..

https://github.com/authpass/authpass/blob/9fa32542a9a1678ff9f220f78f6ad26737fc2fa7/authpass/lib/ui/widgets/keyboard_handler.dart#L16-L17

😂 I actually hoped that someone would come out with a nice pub package which makes this easier ;-) This should be a pretty generic problem to solve :)

**Comment by hpoul** [comment]
@lijy91 thanks for the update of `hotkey_manager` 👍 i've seen you're using it in the biyi_app app - do you plan on providing user's a way to customize hotkeys in your app? 😅️ Just thinking how this could be implemented the easiest way..

**Comment by hpoul** [comment]
@lijy91 are there any external dependencies for linux? [the build seems to fail with](https://github.com/authpass/authpass/pull/262/checks?check_run_id=3471481685#step:8:329):

```
[  +43 ms] -- Checking for module 'keybinder-3.0'
[   +2 ms] --   No package 'keybinder-3.0' found
```

**Comment by lijy91** [comment]
> @lijy91 are there any external dependencies for linux? [the build seems to fail with](https://github.com/authpass/authpass/pull/262/checks?check_run_id=3471481685#step:8:329):
> 
> ```
> [  +43 ms] -- Checking for module 'keybinder-3.0'
> [   +2 ms] --   No package 'keybinder-3.0' found
> ```

On linux platform it depends on `keybinder-3.0`, You need to install it.

```
sudo apt-get install keybinder-3.0
```

**Comment by hpoul** [comment]
@lijy91 thanks.. is this "only" a compile time dependency, or must this also be installed during runtime?

I'm now getting the following compile errors https://github.com/authpass/authpass/pull/262/checks?check_run_id=3472093090#step:8:506

```

[        ] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:23:15: error: no member named 'string' in namespace 'std'
[   +4 ms] std::map<std::string, uint> known_virtual_key_codes = {
[        ]          ~~~~~^
[   +1 ms] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:254:15: error: no member named 'string' in namespace 'std'
[        ] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:279:3: error: no type named 'string' in namespace 'std'; did you mean 'GString'?
[        ] std::map<std::string, std::string> hotkey_map;
[        ]          ~~~~~^
[   +1 ms]   std::string val = keystring;
[        ]   ^~~~~~~~~~~
[        ] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:301:39: error: no member named 'string' in namespace 'std'
[        ]   GString
[        ] /usr/include/glib-2.0/glib/gstring.h:39:33: note: 'GString' declared here
[        ] typedef struct _GString         GString;
[        ]                                 ^
[   +1 ms] guint get_mods(const std::vector<std::string> &modifiers)
[        ]                                  ~~~~~^
[        ] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:327:20: error: no member named 'string' in namespace 'std'
[        ] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:327:28: error: C++ requires a type specifier for all declarations
[        ]   std::vector<std::string> modifiers;
[        ]               ~~~~~^
[        ]   std::vector<std::string> modifiers;
[        ] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:330:5: error: no type named 'string' in namespace 'std'; did you mean 'GString'?
[        ]                            ^
[        ]     std::string keyModifier = fl_value_get_string(fl_value_get_list_value(modifiers_value, i));
[        ]     ^~~~~~~~~~~
[        ]     GString
[        ] /usr/include/glib-2.0/glib/gstring.h:39:33: note: 'GString' declared here
[        ] typedef struct _GString         GString;
[        ]                                 ^
[        ] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:338:36: error: no member named 'string' in namespace 'std'
[        ]   hotkey_map.insert(std::pair<std::string, std::string>(identifier, keystring));
[        ]                               ~~~~~^
[        ] /home/runner/work/authpass/authpass/authpass/linux/flutter/ephemeral/.plugin_symlinks/hotkey_manager/linux/hotkey_manager_plugin.cc:352:3: error: no type named 'string' in namespace 'std'; did you mean 'GString'?
[        ]   std::string val = identifier;
[        ]   ^~~~~~~~~~~
[        ]   GString
[        ] /usr/include/glib-2.0/glib/gstring.h:39:33: note: 'GString' declared here
[        ] typedef struct _GString         GString;
[        ]                                 ^
[        ] 9 errors generated.
```

**Comment by lijy91** [comment]
@hpoul I think this may be caused by the build environment, I tried adding `#include <string>` to my code, you can update `hotkey_manager` to `0.0.6`, if it still fails to build I may need to add a github action for `hotkey_manager` to verify it.

I use `Ubuntu 20.04.1 LTS` for testing

**Comment by hpoul** [comment]
@lijy91 thanks! that seems to have done the trick. The linux build uses ubuntu-18.04 - maybe that's the difference. Now I just need a way to find a way to try the runtime 😂️ too many platforms :-)

**Comment by hpoul** [comment]
okay, this seems to be a runtime dependency as well 🙄 starting to get a bit annoying to have more dependencies a user must install just for a single shortcut nobody is going to use 🤣 but anyway..

Screen Shot 2021-08-31 at 20 25 28

**Comment by hpoul** [comment]
@rburgst did you test on windows or macos whether the global system wide keys where working correctly?

**Comment by lijy91** [comment]
@hpoul `hotkey_manager` v0.1.0 is released. Please upgrade it.

**Comment by hpoul** [comment]
Great, I've updated `hoteky_manager` and `window_manager` to their latest versions. I'll merge, let's hope for the best 😅️ I can't really test windows or linux.. but at least it compiles.. 🤞

**Pull request merged**
