### PR TITLE
Support changing to custom icons (for groups and entries)

### PR DESCRIPTION
**Pull request by PatrikKoscelansky**
Implemented functionality to select custom icons for both entries and groups.

### CODE REVIEW

**Comment by hpoul** [comment]
Hey, thanks for your work 👍️ looks good ;-)
Did you also make changes to the kdbx.dart package? can you please add your email address you used for committing to [your github account](https://github.com/settings/emails)? this would make the CLA bot happy

**Comment by PatrikKoscelansky** [comment]
Happy to help! 🙂 Regarding kdbx.dart package, I only changed customIcon setter in kdbx_object.dart little bit (I added `}else{` , because otherwise customIconUuid would be set to null right after it was set to icon.uuid ). This way it worked.

image

However, I can't see this change in [Files changed](https://github.com/authpass/authpass/pull/187/files) .

**Comment by hpoul** [comment]
that's because kdbx.dart is it's [own repository](https://github.com/authpass/kdbx.dart) and only integrated as submodule. (if you change into `deps/kdbx.dart` and do a `git status` you should see the changes). you can either create a separate PR there, or i'll just make that small change, no problem as well :-)

**Comment by PatrikKoscelansky** [comment]
ok, I've just created new PR for kdbx.dart

**Review by hpoul — CHANGES_REQUESTED** [review]
thanks, looks good 👍️ seems to work pretty well, just a few minor notes 😅️ please clean up the commented out code, and externalize strings to make them translatable..

ie. all string literals should be put into `app_en.arb` and then accessed through `AppLocalizations` - let me know if you need help with that.. (flutter will create `AppLocalizations` automatically through `app_en.arb` when launching/hot reloading) ( https://flutter.dev/go/i18n-user-guide )

**Comment by PatrikKoscelansky** [comment]
Hi @hpoul . I made requested changes. Hopefully it's correct now. Would you check?

**Comment by hpoul** [comment]
sorry for the late reply.. looks good 👍️ thanks 😻️
i've just made three small changes @ https://github.com/authpass/authpass/pull/187/commits/4b5c139ccd4bca792fac61721e508df7b3f28be6

* add padding to custom icons (otherwise it was not really visible which custom icon was selected in the selector)
* fix size warning for large png files (it did `return` even if the user chose to confirm it) - also the png *error* was also a confirmation dialog (cancel, ok) vs. just a alert dialog (ok) - there is no way ignore this error if it's not a png file.
* improve externalized string descriptions.

**Pull request merged**
