### PR TITLE
Added remove file from recent opened files

### PR DESCRIPTION
**Pull request by saurabh-m-w**
Fixes #260

### CODE REVIEW

**Review by hpoul — CHANGES_REQUESTED** [review]
thanks for the PR 👍️
do you think you could change that to be like a context menu - for example like the group list does it:

https://github.com/authpass/authpass/blob/31e7341b08aedc37cd3d112841352aa3028a9b96/authpass/lib/ui/screens/group_list.dart#L604-L650

currently it would only show one option - something like "Remove from list". (I wouldn't call it "Remove recent file" because it does not remove/delete the file. It just hides it from the list.

thanks!

**Comment by saurabh-m-w** [comment]
hey is that @hpoul  correct?
screenshot1 (1)
screenshot1 (2)

**Comment by hpoul** [comment]
Looks good! As long as it actually disappears from the list? 🤔️ Is it not refreshing?

I'm still thinking about the wording.. maybe we should call it literally "Hide from list", any thoughts?

**Comment by saurabh-m-w** [comment]
> Looks good! As long as it actually disappears from the list? 🤔️ Is it not refreshing?
> 
> I'm still thinking about the wording.. maybe we should call it literally "Hide from list", any thoughts?

It is refreshing perfectly.
Yeah we can have like "Hide from list" ,
but after reopening that file , it will appear on recent list.
So is that you wanted or should we have to delete it from local storage ?

**Comment by hpoul** [comment]
for now I would just hide it once.. and that's it.. we can in a later step show a "Delete file" menu item next to it for **local** files. But lets first finish the "hide"

**Comment by saurabh-m-w** [comment]
> for now I would just hide it once.. and that's it.. we can in a later step show a "Delete file" menu item next to it for **local** files. But lets first finish the "hide"

Yeah,check once updated screenshots.

> hey @hpoul is that correct?
> screenshot1 (1)
> screenshot1 (2)

**Comment by hpoul** [comment]
yep, screenshots look good!

**Comment by saurabh-m-w** [comment]
hey I commited the code ,but what's the issue in **checks**?

**Comment by hpoul** [comment]
It looks like `./lib/ui/screens/select_file_screen.dart` is not formatted correctly. make sure to use `flutter format` - see also https://flutter.dev/docs/development/tools/formatting
I personally simply use the "format on save" option from intellij/android studio.

Also make sure that `flutter analyze` returns no warnings. (Or check the `Analyzer` tool in android studio)

**Review by hpoul — APPROVED** [review]

**Comment by hpoul** [comment]
great thanks.. I've just added CHANGELOG and changed the `GestureDetector` to an `IconButton` - Was there a reason for not using the IconButton? 🤔️
looks good, merging.

**Pull request merged**
