### PR TITLE
actions workflow to build debs

### PR DESCRIPTION
**Pull request by GameTec-live**
In this pull request i added a github actions workflow and debian folder with all of the nescesary items to go and build a debian package as an artifact (the item of the workflow). it uses the latest release and builds a deb file. the only problem rn is, that it doesnt automatcially update the version info of the deb. (i will prob look at it soon and make a new pr!)

Context: #272

### CODE REVIEW

**Comment by GameTec-live** [comment]
im to stupid to understand why tf this cla bot doesnt turn green... prob broken...

**Comment by GameTec-live** [comment]
> im to stupid to understand why tf this cla bot doesnt turn green... prob broken...

i signed it now 3 times and it still os yellow...

**Comment by hpoul** [comment]
> i signed it now 3 times and it still os yellow...

that's probably because [your commits are not associated with your git user. You would have to configure the correct email address for git](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user).
If you like I can try to change the commit to use your email address, would that be okay?

**Comment by GameTec-live** [comment]
sure, but the commit should be linked.... anyways, heres my mail:
benedikt.werner08@gmail.com

**Comment by GameTec-live** [comment]
added stuff to in theory do versioning

**Comment by GameTec-live** [comment]
versioning works!
now im done and its ready to merge!

**Comment by GameTec-live** [comment]
you know, that the upload artifact needs the .deb extension @hpoul?

**Comment by GameTec-live** [comment]
[9399fc1](https://github.com/authpass/authpass/pull/310/commits/9399fc11b3f08c52ca68563efa8c8b8b15f72f11 ok, thats a thing i could have done too... sry XD

**Comment by hpoul** [comment]
@GameTec-live i think it looks good right now.. maybe you could give the generated deb file one last try.. (I don't have a linux right now): https://data.authpass.app/data/artifacts/authpass-linux-1.9.6_1916.deb if everything works with that naming i'll merge it 👍

btw. do you have any idea why the .deb package as 10M vs. the .tar.gz 14MB? 🤔

**Comment by GameTec-live** [comment]
the deb is basically a tar.gz and i have no clue how it can be smaller than the original... gimme a sec to try the deb file...

Also: why do we run the postsetup tools from the repo? i only use the repo for my debian prefab files...
image

**Comment by GameTec-live** [comment]
the deb seems fine and fully functional! have fun :) and maybe awnser the question before u merge... thx!

**Comment by hpoul** [comment]
The `postdeploy` script just decrypts a few secrets.. in this case so I can upload the debian package to my web server.. (it requires a secret token).

Okay perfect.. Then i'll merge ;-) Btw. if you've got some more time to spend, maybe you could take a look if it's feasible to create a debian repo.. afaik it would be a matter of creating the correct file structure hosted via http.. https://wiki.debian.org/DebianRepository/Setup

**Comment by GameTec-live** [comment]
@hpoul a github pages repo could be a http server for that... and if it decrypts some secrets, wouldnt it be stupid to make that script public? anyways, ima look at the setup thingy...

**Comment by hpoul** [comment]
> decrypts some secrets, wouldnt it be stupid to make

the script is public, but the decryption key is not :-) that's why it won't work in your repo.. because it's configured through [github's encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)

**Pull request merged**
