### PR TITLE
snap: use strict mode

### PR DESCRIPTION
**Pull request by kenvandine**
Reorganize the yaml a bit
* use strict mode
* use appropriate plugs
* use the gnome-3-28 snapcraft extension for improved desktop integration.

Please let me know if you have any snap related issues in the future, I'm happy to help.

### CODE REVIEW

**Comment by hpoul** [comment]
@kenvandine thanks, but now I run into this strange error `[Errno 17] File exists: 'libbsd.so.0.8.7' -> '/code/authpass/stage/lib/x86_64-linux-gnu/libbsd.so.0'`

full output:

```
root@c302749c71d8:/code/authpass# snapcraft
The following snaps are required but not installed as snapcraft is running inside docker or podman container: core18, gnome-3-28-1804, gtk-common-themes.
Please ensure the environment is properly setup before continuing.
Ignore this message if the appropriate measures have already been taken
Hit http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                              
Hit http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                                      
Hit http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                                    
Hit http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                                    
Fetched 0 B in 0s (0 B/s)                                                                                                                                          
Pulling authpass 
Pulling gnome-extension 
Building authpass 
Building gnome-extension 
make -j4
gcc -Wall -O2 -o bindtextdomain.so -fPIC -shared ./../src/bindtextdomain.c -ldl
make install DESTDIR=/code/authpass/parts/gnome-extension/install
install -d /code/authpass/parts/gnome-extension/install/gnome-platform
install -d /code/authpass/parts/gnome-extension/install/data-dir
install -d /code/authpass/parts/gnome-extension/install/data-dir/icons
install -d /code/authpass/parts/gnome-extension/install/data-dir/sounds
install -d /code/authpass/parts/gnome-extension/install/data-dir/themes
install -D -m755 desktop-launch "/code/authpass/parts/gnome-extension/install/snap/command-chain"/desktop-launch
install -D -m644 bindtextdomain.so "/code/authpass/parts/gnome-extension/install/lib"/bindtextdomain.so
Staging authpass 
Sorry, an error occurred in Snapcraft:
[Errno 17] File exists: 'libbsd.so.0.8.7' -> '/code/authpass/stage/lib/x86_64-linux-gnu/libbsd.so.0'
```

**Comment by kenvandine** [comment]
@hpoul can you try again? I just rebuilt the docker image, maybe it just needed refreshed deps.  I haven't had any other reports of issues though.

**Comment by hpoul** [comment]
@kenvandine I've tried again with docker pull, then inside the container `snapcraft clean && snapcraft`

<details>
<summary>Unfortunately the same error</summary>

```

root@3eae7bf03771:/code/authpass# cat /tmp/tmp2vgvx9cp/trace.txt
Traceback (most recent call last):
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/file_utils.py", line 109, in link_or_copy
    link(source, destination, follow_symlinks=follow_symlinks)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/file_utils.py", line 143, in link
    os.link(source_path, destination, follow_symlinks=False)
OSError: [Errno 5] Input/output error: '/code/authpass/parts/authpass/install/lib/x86_64-linux-gnu/libbsd.so.0' -> '/code/authpass/stage/lib/x86_64-linux-gnu/libbsd.so.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/snapcraft/current/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==4.0.4', 'console_scripts', 'snapcraft')()
  File "/snap/snapcraft/current/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/cli/_runner.py", line 102, in run
    snap_command.invoke(ctx)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/cli/_command.py", line 88, in invoke
    return super().invoke(ctx)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 273, in snap
    _execute(steps.PRIME, parts=tuple(), pack_project=True, output=output, **kwargs)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 78, in _execute
    lifecycle.execute(step, project_config, parts)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 137, in execute
    executor.run(step, part_names)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 191, in run
    self._handle_step(part_names, part, step, current_step, cli_config)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 205, in _handle_step
    getattr(self, "_run_{}".format(current_step.name))(part)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 269, in _run_stage
    self._run_step(step=steps.STAGE, part=part, progress="Staging")
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 325, in _run_step
    getattr(part, step.name)()
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 832, in stage
    self._do_runner_step(steps.STAGE)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 268, in _do_runner_step
    return getattr(self._runner, "{}".format(step.name))()
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/_runner.py", line 100, in stage
    steps.STAGE,
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/_runner.py", line 171, in _run_scriptlet
    scriptlet_name, function_call.strip()
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/_runner.py", line 227, in _handle_builtin_function
    function(**function_args)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 856, in _do_stage
    fixup_func=fixup_func,
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 1247, in _migrate_files
    file_utils.link_or_copy(src, dst, follow_symlinks=follow_symlinks)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/file_utils.py", line 117, in link_or_copy
    copy(source, destination, follow_symlinks=follow_symlinks)
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/file_utils.py", line 166, in copy
    shutil.copy2(source, destination, follow_symlinks=follow_symlinks)
  File "/snap/snapcraft/current/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/snap/snapcraft/current/usr/lib/python3.6/shutil.py", line 118, in copyfile
    os.symlink(os.readlink(src), dst)
FileExistsError: [Errno 17] File exists: 'libbsd.so.0.8.7' -> '/code/authpass/stage/lib/x86_64-linux-gnu/libbsd.so.0'
root@3eae7bf03771:/code/authpass# 

```

</details>

**Comment by kenvandine** [comment]
@hpoul I'll try to build this myself in docker and see if I can figure it out.

**Comment by hpoul** [comment]
btw. there was an error in the snapcraft.yaml, seems while merging the `plugs` were duplicated.. unforunately this didn't fix anything, still weird that there was no error :) just figured it out because i tried configuring the [build from github](https://snapcraft.io/build) feature and it told me invalid yaml file.

btw. is there some way to simply execute a bash script or something to download binary release? because the [build process is not really trivial](https://github.com/authpass/authpass/blob/master/.github/workflows/linux.yml) i've seen there is a way to use python plugins or a Makefile .. would that be the way to go? The easiest would be to have github build the linux binary, and let snapcraft.io build the snap :-)

**Comment by kenvandine** [comment]
> btw. there was an error in the snapcraft.yaml, seems while merging the `plugs` were duplicated.. unforunately this didn't fix anything, still weird that there was no error :) just figured it out because i tried configuring the [build from github](https://snapcraft.io/build) feature and it told me invalid yaml file.
> 
> btw. is there some way to simply execute a bash script or something to download binary release? because the [build process is not really trivial](https://github.com/authpass/authpass/blob/master/.github/workflows/linux.yml) i've seen there is a way to use python plugins or a Makefile .. would that be the way to go? The easiest would be to have github build the linux binary, and let snapcraft.io build the snap :-)

You could have the source in the snapcraft.yaml reference a URL which is a tarball of the binary.  With the dump plugin, that would just extract that tarball.

**Comment by kenvandine** [comment]
@hpoul You really need to use our ubuntudesktop/gnome-3-28-1804 container.  We need the container to be based on ubuntu 18.04.

I did the following which worked for me.


`
docker run -v $PWD:/home/authpass -it ubuntudesktop/gnome-3-28-1804
root@ba0c112ea892:/# cd /home/authpass/
root@ba0c112ea892:/home/authpass# snapcraft 
...
The following snaps are required but not installed as snapcraft is running inside docker or podman container: core18.
Please ensure the environment is properly setup before continuing.
Ignore this message if the appropriate measures have already been taken
Skipping pull authpass (already ran)
Skipping pull gnome-3-28-extension (already ran)
Skipping build authpass (already ran)
Skipping build gnome-3-28-extension (already ran)
Skipping stage authpass (already ran)
Skipping stage gnome-3-28-extension (already ran)
Skipping prime authpass (already ran)
Skipping prime gnome-3-28-extension (already ran)
The requested action has already been taken. Consider
specifying parts, or clean the steps you want to run again.
Could not find the 'snap' command, validation of advanced snap features shall take place once this snap is uploaded to the Snap Store.
Snapping 'authpass' |                                                                       
Snapped 'authpass_1.6.3+1_amd64.snap'
`

**Comment by hpoul** [comment]
@kenvandine i'm still experiencing the same thing. I'm starting to feel like this is caused because it's a mounted volume from a mac host.. there is something weird going on.. the code tries to first hardlink the file, and if it fails it copies it.. and from the looks of it.. the hardlink creation throws an error, but still creates the hardlink.. so when it afterwards tries to copy it, the file already exists.. it's easy to reproduce:

```
root@1051363b90ac:/home/authpass/tmp# touch first ; ln -s first symlink ; ln symlink hardlink
ln: failed to create hard link 'hardlink' => 'symlink': Input/output error
root@1051363b90ac:/home/authpass/tmp# ls -l
total 0
-rw-r--r-- 2 root root 0 Jun 13 10:53 first
-rw-r--r-- 2 root root 0 Jun 13 10:53 hardlink
lrwxrwxrwx 1 root root 5 Jun 13 10:53 symlink -> first
```

the same command giving outside a mounted volume works.. i assume when the mounted volume itself is linux, it also works.. 

it seems to work when I change /snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/file_utils.py `link_or_copy` to always copy symlinks.. hardlinks on symlinks seems to be bad:

```
    try:
        if not follow_symlinks and os.path.islink(source):
            copy(source, destination)
        else:
            link(source, destination, follow_symlinks=follow_symlinks)
```

with this change building works.. and i pushed it into beta (I think). maybe you can take a look?

**Comment by hpoul** [comment]
@kenvandine fyi, I've now managed to test it on an old PC with native ubuntu installation, and everything seems to work, so i've published it to stable :-) thanks for your help. I've also created a PR for that python change https://github.com/snapcore/snapcraft/pull/3174 .. i guess it's a pretty rare edge case, but i think copying a symlink makes more sense than hardlinking it anyway..

**Pull request merged**
