### PR TITLE
Translated all missing messages to German

### PR DESCRIPTION
**Pull request by stalkopat**
Added a few translations aswell as fixing one typo.

### CODE REVIEW

**Comment by hpoul** [comment]
das ist mir jetzt etwas peinlich. thanks for the work 👍️ but we are actually using https://translate.authpass.app/authpass for translations.. 😅️
I think I should be able to import the translations, since you translated quite a few doing it manually would be probably quite some work. Please use the translation tool for future translations.

What do you think would be a good place to document this, so others see it? 🤔️ unfortunately i can't add comments to the `po` files.. I guess i should add a warning to the `CONTRIBUTING.md`

thanks,
  Herbert

**Comment by stalkopat** [comment]
I discovered the issue #78  ~ 30 minutes after finishing translation. I was under the impression that crowdin just works on the files inside git and imports / synces with the .arb files. My bad.

But when looking at Crowdin i noticed that it lacks context in wich the messages appear inside the Application.

I guess a notice inside contributing.md would be helpful, or maybe a comment inside l10n.yaml since there are Links to Documentation in there.

Sorry dafür, sollte nächstmal erst die Issue's durchsuchen. 🤔

**Comment by hpoul** [comment]
> I guess a notice inside contributing.md would be helpful, or maybe a comment inside l10n.yaml since there are Links to Documentation in there.

`l10n.yaml` is a great idea, will do that :-)

**Comment by hpoul** [comment]
fyi, crowdin imports the app_en.arb and exports all other app_*.arb .. I'm not 100% sure if it would overwrite changes or if it's smart enough to figure it out.. bug at the very least git would probably create a few merge conflicts 🤔️ but i should be able to upload .arb files manually..

**Comment by hpoul** [comment]
Seems crowdin was able to pick up the translations.. it only didn't like the sort order 🤣️ https://github.com/authpass-l10n/authpass/pull/19/files

I've now updated the documentation a bit: https://github.com/authpass/authpass/compare/f1190f6ad55f09abf0ac3e9a4d51e37f0a54494b...527deb16ac34bebd49c2ae44141f98b0c15aefe7

thanks again for the translations :)

**Pull request merged**
